package wibiral.tim.newjavachr.tracing;

import wibiral.tim.javachr.constraints.Constraint;
import wibiral.tim.javachr.constraints.ConstraintStore;
import wibiral.tim.javachr.rules.Rule;

/**
 * Base class for tracers that help debugging by tracing the execution order of the rule execution.
 * Derived class may implement tracing for command line or with a graphical interface.
 */
public abstract class Tracer {
    /**
     * The ConstraintHandler tells the Tracer the last applied rule, the constraints to which the rule was applied and
     * the new constraints generated by the rule.
     * @param appliedRule The Rule that was applied.
     * @param oldConstraints Constraints to which the rule was applied.
     * @param addedConstraints New Constraints generated by the rule.
     * @return False if execution should be stopped, true if Handler should execute next step.
     */
    public abstract boolean step(Rule appliedRule, Constraint<?>[] oldConstraints, Constraint<?>[] addedConstraints);

    public abstract void startMessage(ConstraintStore store);

    public abstract void stopMessage(ConstraintStore store);

    public abstract void terminatedMessage(ConstraintStore store);
}
